1\. 导入numpy库并简写为 np (★☆☆)

In [5]:
import numpy as np

2\. 打印numpy的版本和配置说明 (★☆☆)

In [9]:
print(np.__version__)
print(np.show_config())

1.14.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']

### 1\. Array

3\. 创建一个长度为10的空向量 (★☆☆)


In [10]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4\. 如何找到任何一个数组的内存大小？ (★☆☆)

In [11]:
# print("%d bytes" % (Z.size * Z.itemsize))
print("{} bytes".format(z.size*z.itemsize))

80 bytes


5\. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [17]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6\. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [20]:
z = np.zeros(10)
z[4] = 1 #zero-indexed
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7\. 创建一个值域范围从10到49的向量(★☆☆)

In [26]:
z = np.arange(10,50) #same as range()
print(type(z))
print(z)

<class 'numpy.ndarray'>
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8\. 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [30]:
z = np.arange(50)  # 0 - 49
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 2\. Matrix

9\. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

In [33]:
A = np.arange(9).reshape(3,-1)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10\. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

In [36]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11\. 创建一个 3x3 的单位矩阵 (★☆☆)

In [37]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12\. 创建一个 3x3x3的随机数组 (★☆☆)¶

In [43]:
Z = np.random.random([3,3,3]) #np.random is a module 
print(Z)

[[[0.90506758 0.23461691 0.38008247]
  [0.36044731 0.30049776 0.96534507]
  [0.44749186 0.07384152 0.6384174 ]]

 [[0.90781195 0.44360851 0.02481056]
  [0.26177728 0.2231668  0.86399539]
  [0.85390686 0.94559022 0.625144  ]]

 [[0.08662026 0.1166356  0.9276975 ]
  [0.40668782 0.93200632 0.60076211]
  [0.04271878 0.50974166 0.67532467]]]


13\. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)¶


In [44]:
A = np.random.random((10,10))
Amax, Amin = A.max(), A.min()
print(Amax, Amin)

0.9980589033439998 0.004631589415067028


14\. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)¶

In [45]:
z = np.random.random(30)
m = z.mean()
print(m)

0.6270993716319823


15\. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)¶

In [54]:
A = np.ones((10,10))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16\. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)¶


In [55]:
A = np.ones(5)