1\. 导入numpy库并简写为 np (★☆☆)

In [1]:
import numpy as np

2\. 打印numpy的版本和配置说明 (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.14.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']

### 1\. Array

3\. 创建一个长度为10的空向量 (★☆☆)


In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4\. 如何找到任何一个数组的内存大小？ (★☆☆)

In [4]:
# print("%d bytes" % (Z.size * Z.itemsize))
print("{} bytes".format(z.size*z.itemsize))

80 bytes


5\. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6\. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [6]:
z = np.zeros(10)
z[4] = 1 #zero-indexed
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7\. 创建一个值域范围从10到49的向量(★☆☆)

In [7]:
z = np.arange(10,50) #same as range()
print(type(z))
print(z)

<class 'numpy.ndarray'>
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8\. 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [8]:
z = np.arange(50)  # 0 - 49
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 2\. Matrix

9\. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

In [9]:
A = np.arange(9).reshape(3,-1)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10\. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11\. 创建一个 3x3 的单位矩阵 (★☆☆)

In [11]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12\. 创建一个 3x3x3的随机数组 (★☆☆)¶

In [12]:
Z = np.random.random([3,3,3]) #np.random is a module 
print(Z)

[[[0.33704195 0.59472433 0.43003907]
  [0.2457036  0.23196058 0.25835575]
  [0.0629216  0.79517081 0.21087784]]

 [[0.43453481 0.3123009  0.53945929]
  [0.13915027 0.96026641 0.82432302]
  [0.89033437 0.73870868 0.71355814]]

 [[0.29898595 0.31986165 0.02490673]
  [0.70779546 0.64610022 0.96594282]
  [0.0616895  0.24788359 0.36181216]]]


13\. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)¶


In [13]:
A = np.random.random((10,10))
Amax, Amin = A.max(), A.min()
print(Amax, Amin)

0.9952295622941181 0.0011499287026701666


14\. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)¶

In [14]:
z = np.random.random(30)
m = z.mean()
print(m)

0.5100180489937629


15\. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)¶

In [15]:
A = np.ones((10,10))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16\. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)¶


In [16]:
A = np.ones((5,5))
A = np.pad(A,pad_width=1,mode="constant",constant_values=(0))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17\. 以下表达式运行的结果分别是什么? (★☆☆)¶

In [17]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 0.1*3)

nan
False
False
nan
False


18\. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)¶

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19\. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)¶

In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20\. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?¶

In [20]:
print(np.unravel_index(100,(6,7,8))) # exactly as the qn description

(1, 5, 4)


21\. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [21]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22\. 对一个5x5的随机矩阵做归一化(★☆☆)¶

In [22]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.9351333  0.         0.4330349  0.25082354 0.75615836]
 [0.81902988 0.9439224  0.89725086 0.61863366 0.57099286]
 [0.58084293 0.54464605 0.08084936 0.44989822 0.90279867]
 [0.60161245 0.73983748 0.28104112 0.28103233 0.70511468]
 [1.         0.67148873 0.94719589 0.85227965 0.48778605]]


In [23]:
Z

array([[0.9351333 , 0.        , 0.4330349 , 0.25082354, 0.75615836],
       [0.81902988, 0.9439224 , 0.89725086, 0.61863366, 0.57099286],
       [0.58084293, 0.54464605, 0.08084936, 0.44989822, 0.90279867],
       [0.60161245, 0.73983748, 0.28104112, 0.28103233, 0.70511468],
       [1.        , 0.67148873, 0.94719589, 0.85227965, 0.48778605]])

23\. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)¶

In [24]:
color = np.dtype([('R',np.ubyte,1),
                  ('G',np.ubyte,1),
                 ('B',np.ubyte,1),
                 ('A',np.ubyte,1)])
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

24\. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)¶

In [25]:
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25\. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)¶

In [26]:
Z = np.arange(11)
Z[(3<Z)&(Z<8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26\. 下面脚本运行后的结果是什么? (★☆☆)

In [27]:
print(sum(range(5),-1))
print(np.sum(range(5),-1)) #axis: last which is axis max

9
10


In [117]:
np.sum(np.arange(10).reshape(2,5),-1)

array([[10, 35]])

27\. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)¶

In [29]:
Z = np.arange(5)
Z**Z # each element expo

array([  1,   1,   4,  27, 256])

In [40]:
2<<Z>>2 
#2>>Z: 2 right shift by * 2 ^(element) 
# >>2: then left shift by /2^2

array([0, 1, 2, 4, 8])

In [66]:
Z<- Z # if Z is less than -Z  

array([False, False, False, False, False])

In [57]:
1j*Z # complex 

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [58]:
Z/1/1 #element-wise integer operation

array([0., 1., 2., 3., 4.])

In [65]:
Z<Z>Z #illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28\. 下列表达式的结果分别是什么?(★☆☆)¶

In [71]:
print(np.array(0)/np.array(0)) #nan

nan


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [72]:
print(np.array(0) // np.array(0)) #integer division: return 0

0


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [83]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


29\. 如何从零位对浮点数组做舍入 ? (★☆☆)¶

In [91]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)),Z)) # abs -> ceil -> assign sign of original elem to the ceil

[ 7.76332414  2.31707257  6.24925027 -8.05241933 -6.64334884  3.45041214
  6.78553258 -8.86346081  1.67011948 -7.30659017] [ 8.  3.  7. -9. -7.  4.  7. -9.  2. -8.]


30\. 如何找到两个数组中的共同元素? (★☆☆)¶

In [92]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[4 5 6 9]


31\. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)¶

In [93]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)/ 0

_ = np.seterr(**defaults)
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32\. 下面的表达式是正确的吗? (★☆☆)¶

In [98]:
print(np.emath.sqrt(-1)) # imaginary number  1j
print(np.sqrt(-1)) # nan
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

1j
nan
False


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


33\. 如何得到昨天，今天，明天的日期? (★☆☆)¶

In [100]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday is " + str(yesterday))
print("Today is " + str(today))
print("Tomorrow is " + str(tomorrow))

Yesterday is 2019-06-23
Today is 2019-06-24
Tomorrow is 2019-06-25


34\. 如何得到所有与2016年7月对应的日期？ (★★☆)

In [101]:
Z = np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35\. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)¶

In [102]:
A = np.ones(3) * 1 
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36\. 用五种不同的方法去提取一个随机数组的整数部分(★★☆)¶

In [103]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[6. 5. 3. 0. 6. 9. 0. 4. 7. 1.]
[6. 5. 3. 0. 6. 9. 0. 4. 7. 1.]
[6. 5. 3. 0. 6. 9. 0. 4. 7. 1.]
[6 5 3 0 6 9 0 4 7 1]
[6. 5. 3. 0. 6. 9. 0. 4. 7. 1.]


37\. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)¶

In [107]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38\. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)¶

In [109]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39\. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)¶

In [112]:
Z = np.linspace(0,1, 11, endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40\. 创建一个长度为10的随机向量，并将其排序 (★★☆)¶

In [113]:
Z = np.random.random(10)
Z.sort() # modify original object
print(Z)

[0.07312788 0.19804117 0.27124292 0.33723159 0.35494528 0.36792616
 0.7821074  0.81120081 0.83318227 0.92367774]


41\.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)¶

In [116]:
Z = np.arange(10)
np.add.reduce(Z)

45

42\. 对于两个随机数组A和B，检查它们是否相等(★★☆)¶

In [123]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
#equal = np.allclose(A,B) # all elements difference within tolerance
# for equal dimension only
print(equal)
equal2 = np.array_equal(A,B)
print(equal)

False
False


43\. 创建一个只读数组(read-only) (★★☆)¶

In [125]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44\. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)¶

In [129]:
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.67037346 0.50770435 0.8048791  0.7914427  0.75691331 0.85366443
 0.11983845 1.166897   0.57171239 0.87685839]
[1.57055239 0.5005616  0.25815667 0.08876703 0.0926487  1.19646743
 0.30256137 0.86232948 0.1554851  1.08629279]


45\. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)¶

In [130]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print(Z)

[0.46119694 0.20556048 0.08620817 0.15011656 0.54108555 0.03287195
 1.         0.29661545 0.32128545 0.24810521]


46\. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)¶

In [133]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47\. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))¶

In [134]:
X = np.arange(8)
Y = X + 0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


48\. 打印每个numpy标量类型的最小值和最大值？ (★★☆)¶

In [136]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49\. 如何打印一个数组中的所有数值? (★★☆)¶

In [142]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50\. 给定标量时，如何找到数组中最接近标量的值？(★★☆)¶

In [146]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])
print(v)

2
2.221047210855409


51\. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组(★★☆)¶

In [147]:
Z = np.zeros(10, [('position',[('x',float,1),('y',float,1)]),
                 ('color',[('r',float,1),
                           ('g',float,1),
                           ('b',float,1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52\. 对一个表示坐标形状为(10,2)的随机向量，找到点与点的距离(★★☆)¶

In [152]:
Z = np.random.random((10,2))
X, Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.09839866 0.27288563 0.34102762 0.86369362 0.9160955
  0.58799397 0.40797791 0.78005226 0.92632694]
 [0.09839866 0.         0.29493847 0.38932375 0.89317343 0.92296013
  0.62686157 0.35426646 0.87543307 0.97014714]
 [0.27288563 0.29493847 0.         0.12326031 0.59850871 0.64346989
  0.33401534 0.27523276 0.7419826  0.67799903]
 [0.34102762 0.38932375 0.12326031 0.         0.52821795 0.61163619
  0.24846459 0.38727605 0.63314011 0.58544597]
 [0.86369362 0.89317343 0.59850871 0.52821795 0.         0.21420694
  0.28153051 0.70181997 0.83204136 0.15949382]
 [0.9160955  0.92296013 0.64346989 0.61163619 0.21420694 0.
  0.40042286 0.6582245  1.02624746 0.36454917]
 [0.58799397 0.62686157 0.33401534 0.24846459 0.28153051 0.40042286
  0.         0.50799295 0.66409277 0.3439843 ]
 [0.40797791 0.35426646 0.27523276 0.38727605 0.70181997 0.6582245
  0.50799295 0.         1.01675917 0.82431095]
 [0.78005226 0.87543307 0.7419826  0.63314011 0.83204136 1.02624746
  0.66409277 1.0167591

In [154]:
# Much faster with scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.09839866 0.27288563 0.34102762 0.86369362 0.9160955
  0.58799397 0.40797791 0.78005226 0.92632694]
 [0.09839866 0.         0.29493847 0.38932375 0.89317343 0.92296013
  0.62686157 0.35426646 0.87543307 0.97014714]
 [0.27288563 0.29493847 0.         0.12326031 0.59850871 0.64346989
  0.33401534 0.27523276 0.7419826  0.67799903]
 [0.34102762 0.38932375 0.12326031 0.         0.52821795 0.61163619
  0.24846459 0.38727605 0.63314011 0.58544597]
 [0.86369362 0.89317343 0.59850871 0.52821795 0.         0.21420694
  0.28153051 0.70181997 0.83204136 0.15949382]
 [0.9160955  0.92296013 0.64346989 0.61163619 0.21420694 0.
  0.40042286 0.6582245  1.02624746 0.36454917]
 [0.58799397 0.62686157 0.33401534 0.24846459 0.28153051 0.40042286
  0.         0.50799295 0.66409277 0.3439843 ]
 [0.40797791 0.35426646 0.27523276 0.38727605 0.70181997 0.6582245
  0.50799295 0.         1.01675917 0.82431095]
 [0.78005226 0.87543307 0.7419826  0.63314011 0.83204136 1.02624746
  0.66409277 1.0167591

53\. 如何将32位的浮点数(float)转换为对应的整数(integer)?¶

In [159]:
Z = np.arange(10,dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


54\. 如何读取以下文件? (★★☆)¶

In [ ]:
np.genfromtxt

55\. 对于numpy数组，enumerate的等价操作是什么？(★★☆)¶

In [160]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56\. 生成一个通用的二维Gaussian-like数组 (★★☆)¶

In [164]:
X, Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-(D-mu)**2 / (2.0*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0