1\. 导入numpy库并简写为 np (★☆☆)

In [1]:
import numpy as np

2\. 打印numpy的版本和配置说明 (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.14.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']

### 1\. Array

3\. 创建一个长度为10的空向量 (★☆☆)


In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4\. 如何找到任何一个数组的内存大小？ (★☆☆)

In [4]:
# print("%d bytes" % (Z.size * Z.itemsize))
print("{} bytes".format(z.size*z.itemsize))

80 bytes


5\. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6\. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [6]:
z = np.zeros(10)
z[4] = 1 #zero-indexed
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7\. 创建一个值域范围从10到49的向量(★☆☆)

In [7]:
z = np.arange(10,50) #same as range()
print(type(z))
print(z)

<class 'numpy.ndarray'>
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8\. 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [8]:
z = np.arange(50)  # 0 - 49
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 2\. Matrix

9\. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

In [9]:
A = np.arange(9).reshape(3,-1)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10\. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11\. 创建一个 3x3 的单位矩阵 (★☆☆)

In [11]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12\. 创建一个 3x3x3的随机数组 (★☆☆)¶

In [12]:
Z = np.random.random([3,3,3]) #np.random is a module 
print(Z)

[[[0.33704195 0.59472433 0.43003907]
  [0.2457036  0.23196058 0.25835575]
  [0.0629216  0.79517081 0.21087784]]

 [[0.43453481 0.3123009  0.53945929]
  [0.13915027 0.96026641 0.82432302]
  [0.89033437 0.73870868 0.71355814]]

 [[0.29898595 0.31986165 0.02490673]
  [0.70779546 0.64610022 0.96594282]
  [0.0616895  0.24788359 0.36181216]]]


13\. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)¶


In [13]:
A = np.random.random((10,10))
Amax, Amin = A.max(), A.min()
print(Amax, Amin)

0.9952295622941181 0.0011499287026701666


14\. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)¶

In [14]:
z = np.random.random(30)
m = z.mean()
print(m)

0.5100180489937629


15\. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)¶

In [15]:
A = np.ones((10,10))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16\. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)¶


In [16]:
A = np.ones((5,5))
A = np.pad(A,pad_width=1,mode="constant",constant_values=(0))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17\. 以下表达式运行的结果分别是什么? (★☆☆)¶

In [17]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 0.1*3)

nan
False
False
nan
False


18\. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)¶

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19\. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)¶

In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20\. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?¶

In [20]:
print(np.unravel_index(100,(6,7,8))) # exactly as the qn description

(1, 5, 4)


21\. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [21]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22\. 对一个5x5的随机矩阵做归一化(★☆☆)¶

In [22]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.9351333  0.         0.4330349  0.25082354 0.75615836]
 [0.81902988 0.9439224  0.89725086 0.61863366 0.57099286]
 [0.58084293 0.54464605 0.08084936 0.44989822 0.90279867]
 [0.60161245 0.73983748 0.28104112 0.28103233 0.70511468]
 [1.         0.67148873 0.94719589 0.85227965 0.48778605]]


In [23]:
Z

array([[0.9351333 , 0.        , 0.4330349 , 0.25082354, 0.75615836],
       [0.81902988, 0.9439224 , 0.89725086, 0.61863366, 0.57099286],
       [0.58084293, 0.54464605, 0.08084936, 0.44989822, 0.90279867],
       [0.60161245, 0.73983748, 0.28104112, 0.28103233, 0.70511468],
       [1.        , 0.67148873, 0.94719589, 0.85227965, 0.48778605]])

23\. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)¶

In [24]:
color = np.dtype([('R',np.ubyte,1),
                  ('G',np.ubyte,1),
                 ('B',np.ubyte,1),
                 ('A',np.ubyte,1)])
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

24\. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)¶

In [25]:
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25\. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)¶

In [26]:
Z = np.arange(11)
Z[(3<Z)&(Z<8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26\. 下面脚本运行后的结果是什么? (★☆☆)

In [27]:
print(sum(range(5),-1))
print(np.sum(range(5),-1)) #axis: last which is axis max

9
10


In [117]:
np.sum(np.arange(10).reshape(2,5),-1)

array([[10, 35]])

27\. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)¶

In [29]:
Z = np.arange(5)
Z**Z # each element expo

array([  1,   1,   4,  27, 256])

In [40]:
2<<Z>>2 
#2>>Z: 2 right shift by * 2 ^(element) 
# >>2: then left shift by /2^2

array([0, 1, 2, 4, 8])

In [ ]:
Z<-

In [54]:
#1j*Z
#Z/1/1
#Z<Z>Z

SyntaxError: invalid syntax (<ipython-input-54-2130adcc5c68>, line 1)

In [56]:
z = np.zeros(2)
z**z

array([1., 1.])